### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by ferristale** [kokororin/nssr#2]
部分配置
````    "method": "chacha20",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": ""
````
错误信息
````
nssr start 6
Traceback (most recent call last):
  File "/home/joech/.nssr/lib/shadowsocks/local.py", line 81, in <module>
    main()
  File "/home/joech/.nssr/lib/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
child_process.js:614
    throw err;
    ^

  Error: Command failed: /home/joech/.nssr/lib/shadowsocks/local.py -c /home/joech/.nss  r/servers/6.json --pid-file /home/joech/.nssr/nssr.pid --log-file /home/joech/.nssr/n  ssr.log -d start
  Traceback (most recent call last):
    File "/home/joech/.nssr/lib/shadowsocks/local.py", line 81, in <module>
      main()
    File "/home/joech/.nssr/lib/shadowsocks/local.py", line 43, in main
      config = shell.get_config(True)
    File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/shell.py", line 299, in get_  config
      check_config(config, is_local)
    File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/shell.py", line 129, in chec  k_config
      encrypt.try_cipher(config['password'], config['method'])
    File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/encrypt.py", line 46, in try  _cipher
      Encryptor(key, method)
    File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/encrypt.py", line 90, in __i  nit__
      random_string(self._method_info[1]))
    File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/encrypt.py", line 119, in ge  t_cipher
      return m[2](method, key, iv, op)
    File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/crypto/sodium.py", line 71,   in __init__
      load_libsodium()
    File "/home/joech/.nssr/lib/shadowsocks/../shadowsocks/crypto/sodium.py", line 42,   in load_libsodium
      raise Exception('libsodium not found')
  Exception: libsodium not found
  
  - child_process.js:574 checkExecSyncError
    child_process.js:574:11
  
  - child_process.js:611 Object.execSync
    child_process.js:611:13
  
  - Cli.js:272 Cli.module.exports.Cli.start
    [lib]/[nssr]/lib/Cli.js:272:20
  
  - nssr-start:3 Object.<anonymous>
    [lib]/[nssr]/bin/nssr-start:3:31
  
  - module.js:660 Module._compile
    module.js:660:30
  
  - module.js:671 Object.Module._extensions..js
    module.js:671:10
  
  - module.js:573 Module.load
    module.js:573:32
  
  - module.js:513 tryModuleLoad
    module.js:513:12
  
  - module.js:505 Function.Module._load
    module.js:505:3
  
  - module.js:701 Function.Module.runMain
    module.js:701:10
````

**Comment by kokororin** [comment]
安装 libsodium

**Comment by ferristale** [comment]
用其他服务器试了下。只要chacha20都不行

**Comment by ferristale** [comment]
安装libsodium后成功开启
